/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 src\components\Lowpoly_Helicopter.gltf --transform 
Files: src\components\Lowpoly_Helicopter.gltf [239.86KB] > C:\Users\axelc\Desktop\portfolio\geii\front\geii-portfolio\Lowpoly_Helicopter-transformed.glb [20.22KB] (92%)
*/


import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('https://bv.univ-poitiers.fr/access/content/user/acalen01/portfolio/Lowpoly_Helicopter-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Propeller.geometry} material={materials.Palette} position={[2700.777, 509.277, 11.211]} />
    </group>
  )
}

useGLTF.preload('https://bv.univ-poitiers.fr/access/content/user/acalen01/portfolio/Lowpoly_Helicopter-transformed.glb')
