declare module '*.webp';
declare module '*.svg';
declare module '*.png';
declare module '~react-pages';
declare module '*.jpg';
declare module '*.pdf';
declare module '*.gif';
declare module '@mui/icons-material/Star';
declare module '@mui/icons-material/StarBorder';
declare module '@3d/LeCanvas.jsx'
