on:
  push:
    branches:
      - prod
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: Upload to WebDAV
    uses: bxb100/action-upload@main
    with:
      provider: webdav
      provider_options: |
        endpoint=${{ secrets.WEBDAV_ENDPOINT }}
        username=${{ secrets.WEBDAV_USERNAME }}
        password=${{ secrets.WEBDAV_PASSWORD }}
